/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.facebook.puzzles.dinoisland.thrift;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class Direction {
  public static final int N = 0;
  public static final int NE = 1;
  public static final int E = 2;
  public static final int SE = 3;
  public static final int S = 4;
  public static final int SW = 5;
  public static final int W = 6;
  public static final int NW = 7;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    N, 
    NE, 
    E, 
    SE, 
    S, 
    SW, 
    W, 
    NW );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(N, "N");
    put(NE, "NE");
    put(E, "E");
    put(SE, "SE");
    put(S, "S");
    put(SW, "SW");
    put(W, "W");
    put(NW, "NW");
  }};
}
