/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package battle;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class AttackResult {
  public static final int SUNK_CARRIER = 1;
  public static final int SUNK_BATTLESHIP = 2;
  public static final int SUNK_DESTROYER = 3;
  public static final int SUNK_SUBMARINE = 4;
  public static final int SUNK_PATROL = 5;
  public static final int HIT = 6;
  public static final int MISS = 7;
  public static final int NOT_YOUR_TURN = 8;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    SUNK_CARRIER, 
    SUNK_BATTLESHIP, 
    SUNK_DESTROYER, 
    SUNK_SUBMARINE, 
    SUNK_PATROL, 
    HIT, 
    MISS, 
    NOT_YOUR_TURN );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(SUNK_CARRIER, "SUNK_CARRIER");
    put(SUNK_BATTLESHIP, "SUNK_BATTLESHIP");
    put(SUNK_DESTROYER, "SUNK_DESTROYER");
    put(SUNK_SUBMARINE, "SUNK_SUBMARINE");
    put(SUNK_PATROL, "SUNK_PATROL");
    put(HIT, "HIT");
    put(MISS, "MISS");
    put(NOT_YOUR_TURN, "NOT_YOUR_TURN");
  }};
}
