# coding=utf-8

'''
Problem 44
23 May 2003

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''

import euler
solutions = []
pentagonals = dict.fromkeys((n*(3*n-1)/2) for n in range(1, 2400))
for i in pentagonals:
  for j in pentagonals:
    if ((i - j) in pentagonals) and ((i + j) in pentagonals):
      solutions.append(abs(i - j))
print min(solutions)
