/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.facebook.puzzles.dinoisland.thrift;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class EntityType {
  public static final int PLANT = 0;
  public static final int HERBIVORE = 1;
  public static final int CARNIVORE = 2;
  public static final int IMPASSABLE = 3;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    PLANT, 
    HERBIVORE, 
    CARNIVORE, 
    IMPASSABLE );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(PLANT, "PLANT");
    put(HERBIVORE, "HERBIVORE");
    put(CARNIVORE, "CARNIVORE");
    put(IMPASSABLE, "IMPASSABLE");
  }};
}
