/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package simon;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class Color {
  public static final int RED = 1;
  public static final int YELLOW = 2;
  public static final int GREEN = 3;
  public static final int BLUE = 4;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    RED, 
    YELLOW, 
    GREEN, 
    BLUE );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(RED, "RED");
    put(YELLOW, "YELLOW");
    put(GREEN, "GREEN");
    put(BLUE, "BLUE");
  }};
}
